export default {
  extensions: {
    ts: 'module',
  },
  failFast: true,
  files: [
    '**/*.spec.js',
    '**/*.test.js',
    '**/test/**/*.js',
    '**/tests/**/*.js',
    '**/__tests__/**/*.js',
    '**/*.spec.ts',
    '**/*.test.ts',
    '**/test/**/*.ts',
    '**/tests/**/*.ts',
    '**/__tests__/**/*.ts',
    '**/*.spec.tsx',
    '**/*.test.tsx',
    '**/test/**/*.tsx',
    '**/tests/**/*.tsx',
    '**/__tests__/**/*.tsx',
    '!**/__tests__/**/__helper__/**/*',
    '!**/__tests__/**/__helpers__/**/*',
    '!**/__tests__/**/__fixture__/**/*',
    '1**/__tests__/**/__fixtures__/**/*',
    '!**/test/**/helper/**/*',
    '!**/test/**/helpers/**/*',
    '!**/test/**/fixture/**/*',
    '!**/test/**/fixtures/**/*',
    '!**/tests/**/helper/**/*',
    '!**/tests/**/helpers/**/*',
    '!**/tests/**/fixture/**/*',
    '!**/tests/**/fixtures/**/*',
  ],
  nodeArguments: ['--loader=ts-node/esm'],
  require: ['ts-node/register/transpile-only'],
  verbose: true,
};
