name: '@srclaunch/dx'
description: Quality of life configuration and tooling for development environments.
author: Steven Bennett <steven@srclaunch.com>
license: MIT
version: 0.1.57
engines:
  node: '>=16'
  npm: '>=16'
  yarn: '>=16'
publishConfig:
  access: private
  registry: https://registry.npmjs.org/
type: module
main: ./dist/index.mjs
types: ./dist/index.d.ts
files:
  - .commitlintrc.mjs
  - .commitlintrc.umd.cjs
  - .eslintrc.mjs
  - .eslintrc.umd.cjs
  - .eslintrc.ui.mjs
  - .eslintrc.ui.umd.cjs
  - .prettierrc.mjs
  - .prettierrc.umd.cjs
  - .stylelintrc.mjs
  - .stylelintrc.umd.cjs
  - .stylelintrc.ui.mjs
  - .stylelintrc.ui.umd.cjs
  - .versionrc.mjs
  - .versionrc.umd.cjs
  - ava.config.mjs
  - ava.config.umd.cjs
  - jest.config.mjs
  - jest.config.umd.cjs
  - tsconfig.json
  - tsconfig.ui.json
module: ./dist/index.mjs
exports:
  .:
    import: ./dist/index.mjs
    require: ./dist/index.umd.cjs
scripts:
  yui: yarn upgrade-interactive
  build: yarn srclaunch build
  release: yarn srclaunch release
devDependencies:
  '@types/node': 17.0.31
  '@microsoft/eslint-plugin-sdl': 0.2.0
  eslint: 8.14.0
  eslint-import-resolver-typescript: 2.7.1
  eslint-plugin-eslint-comments: 3.2.0
  eslint-plugin-functional: 4.2.1
  eslint-plugin-import: 2.26.0
  eslint-plugin-node: 11.1.0
  eslint-plugin-only-warn: 1.0.3
  eslint-plugin-regexp: 1.7.0
  eslint-plugin-simple-import-sort: 7.0.0
  eslint-plugin-sort-keys-fix: 1.1.2
  eslint-plugin-sort-requires: 2.1.0
  eslint-plugin-unicorn: 42.0.0
  eslint-config-prettier: 8.5.0
  eslint-plugin-prettier: 4.0.0
  prettier: 2.6.2
  standard-version: 9.3.2
  '@srclaunch/cli': 0.1.437
  '@srclaunch/types': 0.1.148
  eslint-config-stylelint: 15.1.0
  stylelint: 14.8.2
  stylelint-config-idiomatic-order: 8.1.0
  stylelint-config-prettier: 9.0.3
  stylelint-config-recommended: 7.0.0
  stylelint-order: 5.0.0
  '@typescript-eslint/eslint-plugin': 5.22.0
  '@typescript-eslint/parser': 5.22.0
  typescript: 4.6.4
