{
  name: "@srclaunch/dx",
  description: Quality of life configuration and tooling for development environments.,
  author: Steven Bennett <steven@srclaunch.com>,
  license: MIT,
  version: 0.1.65,
  engines: { node: ">=16", yarn: ">=3.2.0" },
  publishConfig: { access: public, registry: https://registry.npmjs.org/ },
  type: module,
  main: ./dist/index.mjs,
  types: ./dist/index.d.ts,
  files:
    [
      .commitlintrc.mjs,
      .commitlintrc.umd.cjs,
      .eslintrc.mjs,
      .eslintrc.umd.cjs,
      .eslintrc.ui.mjs,
      .eslintrc.ui.umd.cjs,
      .prettierrc.mjs,
      .prettierrc.umd.cjs,
      .stylelintrc.mjs,
      .stylelintrc.umd.cjs,
      .stylelintrc.ui.mjs,
      .stylelintrc.ui.umd.cjs,
      .versionrc.mjs,
      .versionrc.umd.cjs,
      ava.config.mjs,
      ava.config.umd.cjs,
      jest.config.mjs,
      jest.config.umd.cjs,
      tsconfig.json,
      tsconfig.ui.json
    ],
  module: ./dist/index.mjs,
  exports:
    {
      "0":
        {
          path: ./.commitlintrc,
          import: ./.commitlintrc.mjs,
          require: ./.commitlintrc.umd.cjs
        },
      "1":
        {
          path: ./.eslintrc,
          import: ./.eslintrc.mjs,
          require: ./.eslintrc.umd.cjs
        },
      "2":
        {
          path: ./.eslintrc.ui,
          import: ./.eslintrc.ui.mjs,
          require: ./.eslintrc.ui.umd.cjs
        },
      "3":
        {
          path: ./.prettierrc,
          import: ./.prettierrc.mjs,
          require: ./.prettierrc.umd.cjs
        },
      "4":
        {
          path: ./.stylelintrc,
          import: ./.stylelintrc.mjs,
          require: ./.stylelintrc.umd.cjs
        },
      "5":
        {
          path: ./.stylelintrc.ui,
          import: ./.stylelintrc.ui.mjs,
          require: ./.stylelintrc.ui.umd.cjs
        },
      "6":
        {
          path: ./.versionrc,
          import: ./.versionrc.mjs,
          require: ./.versionrc.umd.cjs
        },
      "7":
        {
          path: ./ava.config,
          import: ./ava.config.mjs,
          require: ./ava.config.umd.cjs
        },
      "8":
        {
          path: ./jest.config,
          import: ./jest.config.mjs,
          require: ./jest.config.umd.cjs
        },
      "9":
        {
          path: ./tsconfig.json,
          import: ./tsconfig.json,
          require: ./tsconfig.json
        },
      "10":
        {
          path: ./tsconfig.ui.json,
          import: ./tsconfig.ui.json,
          require: ./tsconfig.ui.json
        },
      ./tsconfig.ui.json: { import: ./tsconfig.ui.json, require: ./tsconfig.ui.json }
    },
  scripts:
    {
      yui: yarn upgrade-interactive,
      qr: yarn srclaunch changesets add --files "." --message "Quick release" --type
        "chore" && yarn srclaunch release --push,
      build: yarn srclaunch build,
      release: yarn srclaunch release
    },
  devDependencies:
    {
      "@microsoft/eslint-plugin-sdl": 0.2.0,
      "@srclaunch/cli": 0.1.509,
      "@srclaunch/types": 0.1.183,
      "@types/node": 17.0.31,
      "@typescript-eslint/eslint-plugin": 5.23.0,
      "@typescript-eslint/parser": 5.23.0,
      eslint: 8.15.0,
      eslint-config-prettier: 8.5.0,
      eslint-import-resolver-typescript: 2.7.1,
      eslint-plugin-eslint-comments: 3.2.0,
      eslint-plugin-functional: 4.2.1,
      eslint-plugin-import: 2.26.0,
      eslint-plugin-node: 11.1.0,
      eslint-plugin-only-warn: 1.0.3,
      eslint-plugin-prettier: 4.0.0,
      eslint-plugin-regexp: 1.7.0,
      eslint-plugin-simple-import-sort: 7.0.0,
      eslint-plugin-sort-keys-fix: 1.1.2,
      eslint-plugin-sort-requires: 2.1.0,
      eslint-plugin-unicorn: 42.0.0,
      prettier: 2.6.2,
      standard-version: 9.3.2,
      typescript: 4.6.4
    },
  packageManager: yarn@3.2.0
}
